### PR TITLE
build(docs): bump the compat of QMC

### PR DESCRIPTION
**Pull request by sathvikbhagavan**
NeuralPDE has a QMC compat of 0.3 in https://github.com/SciML/NeuralPDE.jl/blob/master/Project.toml#L69
This resulted in doc build erroring out. Example in master - https://buildkite.com/julialang/neuralpde-dot-jl/builds/1925#018bb11c-4ba3-46ae-b3f8-349a55bc09b7

### CODE REVIEW

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas

This PR was to update QMC compat in the docs as it was introduced in https://github.com/SciML/NeuralPDE.jl/pull/760 which resulted in doc builds erroring out on master - https://buildkite.com/julialang/neuralpde-dot-jl/builds/1925#018bb11c-4ba3-46ae-b3f8-349a55bc09b7/114-117

The builds took a long time (https://buildkite.com/julialang/neuralpde-dot-jl/builds/1933#018c1680-2060-4f60-8d2c-633b3242f739) (16 hrs and errored out), so I tried to bump down QMC and check but that didn't help (same problem).

Looking at the Documenter logs, I ran the last file that it is seemingly stuck on locally and it works fine.

The last successful build on master - https://buildkite.com/julialang/neuralpde-dot-jl/builds/1901#_

Any idea what might be happening?

**Comment by ChrisRackauckas** [comment]
You might be getting line search failures? Is it a BFGS?

**Comment by sathvikbhagavan** [comment]
> You might be getting line search failures? Is it a BFGS?

It is using BFGS. I am not sure if its a line search failure in CI as it works locally. I have changed it to use `BackTracking` for that example. Lets see if that helps.

**Comment by sathvikbhagavan** [comment]
closing in favour of https://github.com/SciML/NeuralPDE.jl/pull/783

**Pull request closed without merging**
