### PR TITLE
fix GPU tests

### PR DESCRIPTION
**Pull request by KirillZubov**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Seems like it's getting stuck?

**Comment by KirillZubov** [comment]
> Seems like it's getting stuck?
it's strange. I ran this example on google collab and the training process doesn't get stuck.

**Comment by ChrisRackauckas** [comment]
@pkofod BFGS isn't compatible with GPUs?

**Comment by KirillZubov** [comment]
The PR can be merged. GPU tests work but over runtime in buildkite.

**Comment by ChrisRackauckas** [comment]
I upped the allowed time on buildkite

**Comment by KirillZubov** [comment]
Two hours will still not be enough for the current tests. I will try to finish the type conversion task(Array -> CuArray) by the next week, it will speed up the execution time, but it will still not be fast enough. I think, it needs to replace the tests, the first test will run more than one hours anyway, and the second does not converge with ADAM only with BFGS and BFGS does not work with GPU.  Instead, it needs more simple tests that will run less than 1 hour.

**Pull request merged**
