### PR TITLE
avoid generators to allow Zygote to handle the sum

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@DhairyaLGandhi this seems... really bad. Are iterators in Zygote overloaded to only work with Float32?

**Comment by DhairyaLGandhi** [comment]
No overloading for specific eltypes. Can you see if forwarding generator to broadcasting would be sufficient in this case?
```julia
 @adjoint function Base.Generator(f,iter)
          y, back = Flux.Zygote.pullback(x -> f.(x), iter)
          y, Δ -> begin
            (nothing, back(Δ)...)
          end
        end
```
This is just for if you need to handle generators; a more performant result might need some benchmarking

**Comment by ChrisRackauckas** [comment]
That gives zero gradients.

**Comment by DhairyaLGandhi** [comment]
Is it interacting with custom adjoints that could be misbehaving? 

Using this adjoint got the generator syntax working without much issue
```julia
julia> Flux.Zygote.gradient(x -> sum(i^2 for i in x), 1:3)
([2, 4, 6],)
```

**Comment by ChrisRackauckas** [comment]
Which custom adjoint?

**Comment by DhairyaLGandhi** [comment]
Probably something in `inner_loss`, because once we get the `Base.Generator` forwarded, there's not much else to that's happening in the adjoint. I also tried

```Julia
julia> Flux.Zygote.gradient(x -> sum(abs2, i^2 for i in x), 1:3)
([4, 32, 108],)
```

**Comment by DhairyaLGandhi** [comment]
It can't handle closures cleanly I suppose, but that should return `nothing` instead of zeros, hence I thought its a custom adjoint being invoked.

**Comment by ChrisRackauckas** [comment]
There is one in FastDense but it's fairly basic and just does linear algebra.

**Pull request merged**
