### PR TITLE
Remove θ

### PR DESCRIPTION
**Pull request by KirillZubov**
Removed θ(the neural network parameters ) from the high-level PDE description.

### CODE REVIEW

**Comment by KirillZubov** [comment]
Theta has remained reserved and can't be used as a parameter of the equation. I wrote a warning to docs.

**Comment by ChrisRackauckas** [comment]
just use a gensym?

**Comment by KirillZubov** [comment]
> just use a gensym?

oh cool, I didn't know about it

**Review by ChrisRackauckas — APPROVED** [review]
anything else needed in this? LGTM

**Pull request merged**
