### PR TITLE
fix 748

### LINKED ISSUE #748: NeuralPDE v.5.9 stops QuasiMonteCarlo from updating
Hey.
I'm having trouble updating `QuasiMonteCarlo` through the REPL. When asked, `pkg` tells me it's  `NeuralPDE`'s fault:
```
(@v1.9) pkg> status --outdated  QuasiMonteCarlo
Status `C:\Users\55619\.julia\environments\v1.9\Project.toml`
⌅ [8a4e6c94] QuasiMonteCarlo v0.2.19 (<v0.3.2): NeuralPDE

(@v1.9) pkg> status NeuralPDE
Status `C:\Users\55619\.julia\environments\v1.9\Project.toml`
  [315f7962] NeuralPDE v5.9.0
```

QMC version 0.2.19 is almost one year old by now. Is this easy to solve or does NeuralPDE use old QMC code internally?

### PR DESCRIPTION
**Pull request by xtalax**
Fixes #748

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Tests fail

**Comment by xtalax** [comment]
Has been integrated in to Astitvas update

**Comment by AstitvaAggarwal** [comment]
@xtalax @ChrisRackauckas the current BPINN tests fail due to a depreciated method, in the Linked PR I've fixed what needs to be added, also a minor BNNODE Bug

**Comment by AstitvaAggarwal** [comment]
@xtalax ive taken in your changes in the linked pr, you can check if tests pass now

**Pull request closed without merging**
