### PR TITLE
add buildkite pipeline

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@DilumAluthge @maleadt trying it out here. Can I do `version: "1"`?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Hmm this doesn't seem to trigger it so I don't quite get what else was done.

**Comment by DilumAluthge** [comment]
I've fixed the Buildkite settings to clone over HTTPS instead of SSH.

Try pushing to this branch again to see if it works.

**Comment by DilumAluthge** [comment]
E.g. delete the GitLab config.

**Comment by ChrisRackauckas** [comment]
how did you change that?

**Comment by DilumAluthge** [comment]
https://buildkite.com/julialang/neuralpde-dot-jl/settings/repository

You'll see a place that says "checkout using". Click the "HTTPS" option instead of the "SSH" option.

**Comment by DilumAluthge** [comment]
Whoops I'm on mobile and accidentally cancelled your build. I've retriggered.

**Comment by DilumAluthge** [comment]
I don't think `version: "1"` is supported yet.

All of the following are supported:
- `version: "1"`
- `version: "1.6-nightly"` (only works during periods of time like now where `release-1.6` has been branched but not released)
- `version: "nightly"`

See also: https://github.com/JuliaCI/julia-buildkite-plugin/issues/3

**Pull request merged**
