### PR TITLE
Remove Flux Support

### PR DESCRIPTION
**Pull request by sathvikbhagavan**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
We should keep a Flux test that shows the auto-translation still works, but internally we won't need any more Flux support beyond that and any other Flux tests beyond a simple translation test can be removed.

**Comment by sathvikbhagavan** [comment]
I am not sure what auto-translation means here? Is there a tool to convert Flux models to Lux? 
NeuralPDE handles Flux and Lux separately with a lot of if-else statements. I basically removed those in this PR and kept the Lux part.

**Comment by ChrisRackauckas** [comment]
> Is there a tool to convert Flux models to Lux?

Yes. `Lux.transform`. https://github.com/SciML/NeuralPDE.jl/pull/783#issuecomment-1902133604

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas this PR is ready. I have also refactored all tests into proper testsets, that's why the diff is big.

I have added the auto translation part:

NNODE - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/src/ode_solve.jl#L90
BNNODE - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/src/BPINN_ode.jl#L116
NNDAE - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/src/dae_solve.jl#L45
PhysicsInformedNN - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/src/pinn_types.jl#L107
BayesianPINN - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/src/pinn_types.jl#L243

I have also added tests for translation from Flux:

NNODE - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/test/NNODE_tests.jl#L220
BNNODE - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/test/BPINN_Tests.jl#L220
PhysicsInformedNN - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/test/NNPDE_tests.jl#L418
BayesianPINN - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/test/BPINN_PDE_tests.jl#L172

I haven't touched NNRODE and have commented out the include statement of the file because I saw their tests were also commented out - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/test/runtests.jl#L47. Should I revive it?

**Comment by ChrisRackauckas** [comment]
> I haven't touched NNRODE and have commented out the include statement of the file because I saw their tests were also commented out - https://github.com/sathvikbhagavan/NeuralPDE.jl/blob/sb/remove_flux/test/runtests.jl#L47. Should I revive it?

No, that needs a lot more work. Keep it separate.

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
