### PR TITLE
Investigating doc failure

### PR DESCRIPTION
**Pull request by sathvikbhagavan**
Investigating docs failure of https://github.com/SciML/NeuralPDE.jl/pull/729

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I already set the optim bound

**Comment by sathvikbhagavan** [comment]
Ok.. what was the reason it was failing in https://buildkite.com/julialang/neuralpde-dot-jl/builds/1875?

**Comment by ChrisRackauckas** [comment]
Optim broke with https://github.com/JuliaNLSolvers/Optim.jl/pull/1034. We're going to need to make an Optim alternative since it has too many problems, and this is accelerating that process.

**Comment by pkofod** [comment]
I can only repeat what I’ve said many times before. These “too many problems” are not consistent with the number of issues opened by sciml developers.

**Pull request closed without merging**
