### PR TITLE
QuasiRandomTraining, on every training iteration, it is generated a new quasirandom sample

### PR DESCRIPTION
**Pull request by KirillZubov**
https://github.com/SciML/NeuralPDE.jl/issues/288

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Resampling should be an option (true by default though).

**Comment by KirillZubov** [comment]
@ChrisRackauckas almost all methods do not support automatic differentiation except GridSample.

```julia
using QuasiMonteCarlo, Distributions,Zygote
lb = [0.1,-0.5]
ub = [1.0,20.0]
n = 5
d = 2

p = Float32.([1.5,2.0])
function testf(p)
     x = Float32.(QuasiMonteCarlo.sample(n,lb,ub,GridSample([0.1,0.5])))
     sum(sin.(x .* p))
end
dp1 = Zygote.gradient(testf,p)
```
for all other methods, this results in an error "Mutating arrays is not supported"
so `resampling` work only with GridSample([0.1,0.5]) and we need to set the step dx

**Comment by ChrisRackauckas** [comment]
I don't get what you mean. `resample` shouldn't work with GridTraining at all because the points would be fixed?

**Comment by KirillZubov** [comment]
GridSample is one of methods in  QuasiMonteCarlo.jl

**Comment by KirillZubov** [comment]
almost all Sampling Methods in QuasiMonteCarlo.jl  https://github.com/SciML/QuasiMonteCarlo.jl#available-sampling-methods

**Comment by KirillZubov** [comment]
and since they do not support automatic differentiation (Zygote don't work with Mutating array), we while cannot use them for resampling (create at runtime on each iteration)

**Comment by ChrisRackauckas** [comment]
Wrap it in a function and do `@nograd` on it. We shouldn't be differentiating the sampling.

**Comment by KirillZubov** [comment]
yeap, thanks ,it works

**Pull request merged**
