### PR TITLE
WIP: PINNs meet FEM

### PR DESCRIPTION
**Pull request by vpuri3**

### CODE REVIEW

**Comment by KirillZubov** [comment]
@vpuri3 there is the article?

**Comment by KirillZubov** [comment]
it needs more hard tests. FFNN does the same with these tests but faster
```julia
plts =[]
function makeplot(phi,p)

    fp = phi(xp, p)

    plt = plot()
    plt = plot!(title=""
               ,xlabel="x",ylabel="y")
    plt = plot!(ylims=(0,Inf))

    plt = plot!(xp',up',width=3,label="data")
    plt = plot!(xp',fp',width=3,label="prediction")

    display(plt)
    push!(plts, plt)

    return plt
end
#--------------------------------------#
function callback(p,l)
    fp  = phi(xp,p)
    ep  = up .- fp
    er  = norm(ep,Inf)
    println("Loss: $l, Pointwise er: $er")
    makeplot(phi,p)
    (l < 1e-6) && return true
    return false
end

@parameters x
@variables u(..)

function utrue(x)
   # u = @. 2 + sin(3.7*pi*x + pi*0.3)
    u = @. sin(x^2 + 3*x)^2 + exp(x)
    # u = @. 3x^2
  # u = @. 2 + abs(x - 0.2)
#   u = @. 1 + sin(10*x)
#   u = @. sin(pi*x)
    return u
end

# regression
eq = [u(x) ~ utrue(x)]
bc = [u(-1f0) ~ utrue(-1f0)
     ,u( 1f0) ~ utrue( 1f0)]

domain = [x ∈ Interval(-1f0,1f0)]
#--------------------------------------#

# for evaluation
xp = Array(range(-1,1,length=100))'
up = utrue(xp)

inn = 12
chain = FastChain(FastDense(1,inn,Flux.tanh),
                  FastDense(inn,inn,Flux.tanh),
                  FastDense(inn,1))

initθ = Float64.(DiffEqFlux.initial_params(chain))
chain(xp,initθ)
# NeuralPDE setup
strategy = GridTraining(0.1)
# strategy = NeuralPDE.QuadratureTraining()
discretization = PhysicsInformedNN(chain,strategy, init_params =initθ)
pdesys = PDESystem(eq,bc,domain,[x],[u])
prob = discretize(pdesys,discretization)

opt2 = BFGS()
sch  = SinExp(λ0=1e-0,λ1=1e-2,γ=5e-1,period=50)
opt1 = Scheduler(sch,ADAM())
opt1 = ADAM()

phi =discretization.phi

phi(xp, initθ)

res  = GalacticOptim.solve(prob,opt2,cb=callback,maxiters=100)

plts
anim = @animate for p ∈ plts
    plot(p)
end
gif(anim, "FFNN.gif", fps=200)
```
classic

**Comment by vpuri3** [comment]
hi @KirillZubov, the work is based on the ideas in https://arxiv.org/abs/2101.11256. Check readme for details. With this method, I am particularly targeting PDEs in complex geometry, and with discontinuities. Will add more details, and some benchmarks.

**Comment by vpuri3** [comment]
eg: 
afn_fem_tri2

**Comment by vpuri3** [comment]
this work will be private for the time being.

**Pull request closed without merging**
