### PR TITLE
[WIP]Strategy for system of pde

### PR DESCRIPTION
**Pull request by KirillZubov**
For the system of pde `sys = [eq1, ..eqn`] we just add aditional condition to loss functions - `sum([eq1, ..eqn])`
and then: 
`pde_loss_func = [eq1, ..eqn].^2 + sum([eq1, ..eqn] )^2`

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
why?

**Comment by KirillZubov** [comment]
how was before in docs: https://neuralpde.sciml.ai/dev/examples/pinns_example/#Example-4-:-Solving-a-PDE-System
and and now, for the same example
image
image
image

**Comment by KirillZubov** [comment]
LV example 
```julia
using OrdinaryDiffEq,  Plots

function ff(du,u,p,t)
  du[1] = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = -p[3]*u[2] + p[4]*u[1]*u[2]
end
function ff(u,p,t)
  [p[1]*u[1] - p[2]*u[1]*u[2],-p[3]*u[2] + p[4]*u[1]*u[2]]
end

p = Float32[1.5,1.0,3.0,1.0]
u0 = Float32[1.0,1.0]
prob = ODEProblem(ff,u0,(0f0,3f0),p)
prob_oop = ODEProblem{false}(ff,u0,(0f0,3f0),p)

true_sol = solve(prob,Tsit5())

@parameters t
@variables u1(..), u2(..)
@derivatives Dt'~t

#LV
dt = 0.1
p = Float32[1.5,1.0,3.0,1.0]
eqs = [Dt(u1(t)) ~ p[1]*u1(t) - p[2]*u1(t)*u2(t),
       Dt(u2(t)) ~ -p[3]*u2(t) + p[4]*u1(t)*u2(t),
       dt*u1(t) ~ 1., dt*u2(t) ~ 1.]
       # Dt(u1(t))~(u1(t+dt)-u1(t-dt))/(2dt),
       # Dt(u2(t))~(u2(t+dt)-u2(t-dt))/(2dt)]
#
# Initial/ boundary/additional conditions
bcs = [u1(0) ~ 1, u2(0) ~ 1]

# Space and time domains
domains = [t ∈ IntervalDomain(0.0,3.0)]

# Neural network
chain1 = FastChain(FastDense(1,12,Flux.σ),FastDense(12,1))
chain2 = FastChain(FastDense(1,12,Flux.σ),FastDense(12,1))
grid_strategy = NeuralPDE.GridTraining(dx= dt)
# iter_strategy = NeuralPDE.IterTraining(dx= dt, iter = maxiters)
discretization = NeuralPDE.PhysicsInformedNN([chain1,chain2],strategy = grid_strategy)
pde_system = PDESystem(eqs,bcs,domains,[t],[u1,u2])
prob = NeuralPDE.discretize(pde_system,discretization)


cb = function (p,l)
    println("Current loss is: $l")
    return false
end

opt =ADAM(0.1)
res = GalacticOptim.solve(prob,opt; cb = cb, maxiters=1000)
phi = discretization.phi

initθ = discretization.initθ
acum =  [0;accumulate(+, length.(initθ))]
sep = [acum[i]+1 : acum[i+1] for i in 1:length(acum)-1]
minimizers = [res.minimizer[s] for s in sep]
ts = [domain.domain.lower:dt/10:domain.domain.upper for domain in domains][1]
u_predict  = [[phi[i]([t],minimizers[i])[1] for t in ts] for i in 1:2]

plot(true_sol)
plot!(ts,  u_predict)
```
image

**Comment by KirillZubov** [comment]
> why?

This gives a better prediction, at least for the examples, I tested.

**Comment by ChrisRackauckas** [comment]
LV still doesn't look good. The difference seems almost random?

**Comment by KirillZubov** [comment]
I investigated and try a couple of strategies, but yes, LV isn't working still.

**Comment by ChrisRackauckas** [comment]
I don't see a strong theoretical or practical argument for this. I'll need to see some more convincing evidence before thinking it's not random.

**Comment by KirillZubov** [comment]
> I don't see a strong theoretical or practical argument for this. I'll need to see some more convincing evidence before thinking it's not random.

yeah, sure

**Pull request closed without merging**
