### PR TITLE
Lux on GPU

### PR DESCRIPTION
**Pull request by MilkshakeForReal**
Need https://github.com/jonniedie/ComponentArrays.jl/pull/164 to actually work

### CODE REVIEW

**Comment by MilkshakeForReal** [comment]
#579

**Review by ChrisRackauckas — APPROVED** [review]
I'll wait on the ComponentArrays PR/release

**Comment by MilkshakeForReal** [comment]
Hi Chris, can I become a member of the [open source organization](https://github.com/SciML)?

**Comment by ChrisRackauckas** [comment]
Sure thing, invite sent.

**Comment by MilkshakeForReal** [comment]
I am honored, thank you!

**Comment by MilkshakeForReal** [comment]
This is not a complete fix. Since
```
adapt(parameterless_type(θ), x)
```
doesn't recognize `GPUComponentArray`. A straightforward solution is to overload `parameterless_type`. Or `getdata` whereever suitable.

**Comment by MilkshakeForReal** [comment]
I moved the overloading of `adapt_storage` here since the owner of `ComponentArrays` is not very responsive. Now it can work alone.

**Comment by ChrisRackauckas** [comment]
Can you open an issue about the upstream to track it? I'll take this for now so it doesn't need to keep waiting.

**Comment by MilkshakeForReal** [comment]
Sure. Could you tag this PR?

**Pull request merged**
