### PR TITLE
Test master

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by xtalax** [comment]
@ChrisRackauckas Why do you keep testing master? Is there stuff going on upstream I should know about?

**Comment by ChrisRackauckas** [comment]
@avik-pal I thought this was handled? https://buildkite.com/julialang/neuralpde-dot-jl/builds/1542#01873299-841b-419c-869b-4f8ae5090b90/505-509

**Comment by avik-pal** [comment]
I am confused what's happening here: https://buildkite.com/julialang/neuralpde-dot-jl/builds/1542#01873299-841b-419c-869b-4f8ae5090b90/299 seems to install v0.1.13 but the `git-tree-sha` not found is for v0.1.12 https://github.com/JuliaRegistries/General/blob/20d99aa5c5ff7a1259b151e5b21a3534804a3871/L/LuxLib/Versions.toml#L38

**Comment by avik-pal** [comment]
https://github.com/JuliaRegistries/General/pull/80666

**Pull request merged**
